---
- name: Include CentOS specific tasks
  include: CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_distribution == "Debian"

- name: Include prometheus node exporter
  include: node_exporter.yml
  when: install_node_exporter == true

- name: Include NAT rules and IPv4 forwarding
  include: nat_forwarding.yml

- name: Include Squid configuration
  include: squid_config.yml

- name: Reload squid, nginx, firewalld
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
  - firewalld
  - nginx
  - squid
