---
- name: Install the latest version of Squid, nginx
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx
    - squid

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_file: /etc/sysctl.d/99-ip_forwarding.conf
    reload: yes

- name: Set the NAT Masquerade iptables rule
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    jump: MASQUERADE

- name: Add squid proxy configuration
  copy:
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0640
    src: squid.conf

- name: Allow squid on the firewall
  firewalld:
    service: squid
    permanent: true
    state: enabled

- name: Download and install prometheus node exporter
  shell: |
    curl -o node_exporter-0.16.0.linux-amd64.tar.gz -L https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    tar -xzvf node_exporter-0.16.0.linux-amd64.tar.gz
    mv node_exporter-0.16.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    executable: /bin/bash
  register: prom_node_exporter_installer

- name: Add prometheus node exporter systemd configuration
  copy:
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0400
    src: node_exporter.service

- name: Allow node exporter on the firewall
  firewalld:
    port: 9090/tcp
    permanent: true
    state: enabled

- name: Reload squid, nginx, firewalld, node_exporter
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
  - firewalld
  - node_exporter
  - nginx
  - squid
